# dnf module disable nodejs -y
# dnf module enable nodejs:20 -y 
# dnf install nodejs -y 
# useradd expense
# mkdir /app 
# curl -o /tmp/backend.zip https://expense-web-app.s3.amazonaws.com/backend.zip 
# cp backend.service /etc/systemd/system/backend.service
# cd /app 
# unzip -o /tmp/backend.zip
# cd /app 
# npm install 
# chmod -R 775 /app
# chown -R expense:expense /app
# dnf install mysql-server -y
# mysql -h 172.31.33.204 -uroot -pExpenseApp@1 < /app/schema/backend.sql
# systemctl daemon-reload
# systemctl enable backend 
# systemctl start backend 

#- name: Set Hostname to {{COMP}}-{{env}}
 # ansible.builtin.shell: set-hostname {{COMP}}-{{env}}

- name: Disable of nodejs
  ansible.builtin.shell: dnf module disable nodejs -y

- name: Enabling of nodejs:20
  ansible.builtin.shell: dnf module enable nodejs:20 -y

- name: Install a package
  ansible.builtin.dnf:
    name: nodejs
    state: present

- name: Add the user {{COMP}}-{{env}}
  ansible.builtin.user:
    name: expense
    comment: App user

- name: Include backend role with vars
  ansible.builtin.include_role:
    name: common
    tasks_from: pre

- name: Install node.js package.
  community.general.npm:
    path: "{{APP_PATH}}"

- name: Install MySQL Server
  ansible.builtin.package:
    name: mysql-server
    state: present

# - name: Inject schema using mysql CLI directly
#   ansible.builtin.shell: mysql -h mysql-{{env}}.exp.in -u root -p{{pwd}} < /app/schema/backend.sql     #ExpenseApp@1
- name: install pymsql
  ansible.builtin.pip:
    name:
      - PyMySQl
      - cryptography
    executable: pip3.11
    
- name: Inject schema
  community.mysql.mysql_db:
    state: import
    name: all
    target: /app/schema/backend.sql
    login_user: root
    login_password: ExpenseApp@1
    login_host: mysql-{{env}}.exp.in

- name: Copy file
  ansible.builtin.template:
    src: backend.service
    dest: /etc/systemd/system/backend.service

- name: ReStart nginx service
  ansible.builtin.systemd:
    name: backend
    state: restarted
    enabled: yes   # Enable to start at boot